#-----------------------------------
#  Colorful Terminal
#-----------------------------------
#
# Tell ls to be colourful
export CLICOLOR=1
export LSCOLORS=Exfxcxdxbxegedabagacad

# Tell grep to highlight matches
export GREP_OPTIONS='--color=auto'

export TERM="xterm-color"
PS1='\[\e[0;33m\]\u\[\e[0m\]@\[\e[0;32m\]\h\[\e[0m\]:\[\e[0;34m\]\w\[\e[0m\]\$ '


#-----------------------------------
#  PATH
#-----------------------------------
#
export PATH="$PATH:$HOME/.composer/vendor/bin"


#-----------------------------------
#  Bash Completion
#-----------------------------------
#
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion


#-----------------------------------
#  SSH AGENT WORKAROUND
#-----------------------------------
#
ssh-add -l &> /dev/null || ssh-add -k ~/.ssh/id_rsa
